name: Android APK Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip and List Files
        run: |
          mkdir build_dir
          unzip -o -q AutoTasleek_New.zip -d build_dir
          echo "محتويات المجلد هي:"
          ls -R build_dir

      - name: Build Debug APK
        run: |
          echo "جاري البناء..."
          
